version: "3"
services:
  api:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
  app:
    build: ./react-client
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

